#!/usr/bin/env bash
#Nginx installation from listening on port 80
apt -get update -y
apt -get install -y nginx
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx enable
sudo service nginx start
