#!/usr/bin/env bash
# This script installs and starts Apache, and sets up a custom index page for the Docker container.

sudo apt-get update -y
sudo apt-get install -y apache2
sudo /etc/init.d/apache2 start
echo "Hello Holberton" |sudo tee -a /var/www/html/index.html
sudo /etc/init.d/apache2 restart
